### ISSUE TITLE
番剧页获取图片过大

### ISSUE THREAD

**Issue by TYblog** [HCLonely/hexo-bilibili-bangumi#10]
**错误描述**

After the normal configuration, it conflicts with the configuration of img in markdown, and the cover image is too large.

I don't know, I don't know how to set a new class for the cover img.

正常配置后，它与markdown中img的配置冲突，并且封面图像太大。

我不知道，我不知道如何为封面img设置一个新类。   主题：hexo-yun

**Comment by HCLonely** [comment]
有没有示例页面我看一下

**Comment by TYblog** [comment]
I did not modify any data under the project

我没有在项目下修改任何数据

https://mpsblog.shop/bangumis/index.html

**Comment by HCLonely** [comment]
这不很正常吗
![image](https://user-images.githubusercontent.com/26346802/93659165-23fb2280-fa75-11ea-86c6-0d0df63f2eec.png)

**Comment by TYblog** [comment]
![image](https://user-images.githubusercontent.com/35173696/93665880-92a7a280-faac-11ea-9a08-5dc54b1c30ec.png)
是不是有什么误会？

**Comment by TYblog** [comment]
![Clip_20200919_192112.png](https://7.dusays.com/2020/09/19/7d299a20b0935.png)
这一页不调整就不出图片，我每次都要调整缩放吗？

**Comment by HCLonely** [comment]
> ![Clip_20200919_192112.png](https://camo.githubusercontent.com/a85df6f268936feb8d6177e8048db8002d4ace71/68747470733a2f2f372e6475736179732e636f6d2f323032302f30392f31392f376432393961323062303933352e706e67)
> 这一页不调整就不出图片，我每次都要调整缩放吗？

这个应该是你使用了什么插件的问题，自动给图片添加了样式
![image](https://user-images.githubusercontent.com/26346802/93666092-db139000-faad-11ea-80c2-e17320b0ad09.png)

**Comment by HCLonely** [comment]
> ![Clip_20200919_191646.png](https://camo.githubusercontent.com/0864a4dbae139e987ad2ae1fe72dfe54f79bca47/68747470733a2f2f372e6475736179732e636f6d2f323032302f30392f31392f383739623365666130373161632e706e67)
> 是不是有什么误会？ 浏览器缩放100%显示不正常。

这个问题我稍后更新一下，应该可以解决

**Comment by TYblog** [comment]
并没有什么改善。

**Comment by HCLonely** [comment]
可是我这边看的并没有什么问题，而且你主题的样式顶掉插件的样式了，我不可能去兼容所有主题。
你可以自己添加样式来控制图片大小。

**Comment by TYblog** [comment]
好的，已经很感谢您了。
