### ISSUE TITLE
github action中hexo bangumi -u运行报错

### ISSUE THREAD

**Issue by 0x7b** [HCLonely/hexo-bilibili-bangumi#11]
INFO  Getting bilibili bangumis, please wait...
(node:3251) UnhandledPromiseRejectionWarning: TypeError: list.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at biliBangumi (/home/runner/work/Hexo-source-code/Hexo-source-code/node_modules/hexo-bilibili-bangumi/index.js:93:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async saveBangumiData (/home/runner/work/Hexo-source-code/Hexo-source-code/node_modules/hexo-bilibili-bangumi/index.js:104:19)
(node:3251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3251) [DEP0018] DeprecationWarning: Unhandled promise rejec

且hexo bangumi update，返回未找到命令

**Comment by 0x7b** [comment]
hexo g中
INFO  Can't find bilibili bangumi data, please use 'hexo bangumi update' command to get data

**Comment by HCLonely** [comment]
插件版本是多少

**Comment by 0x7b** [comment]
> 插件版本是多少

"hexo-bilibili-bangumi": "^1.1.10"

**Comment by HCLonely** [comment]
更新到最新版就可以了

**Comment by 0x7b** [comment]
已经解决，谢谢大佬
