### ISSUE TITLE
在使用butterfly主题，开始图片懒加载的情况下。进入博客番剧页面，番剧封面会一直显示加载图片。

### ISSUE THREAD

**Issue by hookind** [HCLonely/hexo-bilibili-bangumi#112]
**错误描述**

在使用butterfly主题，开始图片懒加载的情况下。进入博客番剧页面，番剧封面会一直显示加载图片。在关闭图片懒加载后，进入番剧页面，番剧封面才会显示。想问一下，能不能在开启图片懒加载的情况下，使番剧图片正常显示。

**报错信息（建议使用截图，请尽量截取全部把错误信息）**

问题页面网址：https://hookind.github.io/bangumis/

**插件版本**

"hexo-bilibili-bangumi": "^1.6.2",

**软件信息（使用`hexo -v`命令查看）**

butterfly: 3.8.4
hexo: 5.4.0
hexo-cli: 4.3.0
os: linux 5.10.60-amd64-desktop Deepin 20.3 20.3
node: 16.13.0
v8: 9.4.146.19-node.13
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

**Comment by HCLonely** [comment]
更新到1.6.3后，把插件的lazyload关掉
