### ISSUE TITLE
[BUG]配合 Shoka 主题使用时无报错但渲染出来的页面不正确

### ISSUE THREAD

**Issue by WhitePaper233** [HCLonely/hexo-bilibili-bangumi#118]
**错误描述**
配合 [Shoka 主题](https://github.com/amehime/hexo-theme-shoka.git) 使用时，渲染页面时并无报错，但渲染出来的页面不完整且无法向下滚动

**报错信息（建议使用截图，请尽量截取全部把错误信息）**
无报错
![截图](https://s2.loli.net/2022/01/03/3tv9NH7o4ugFXbk.png)

**插件版本**
Latest

**软件信息（使用`hexo -v`命令查看）**
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 17.3.0
v8: 9.6.180.15-node.12
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 3.0.1+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

**Comment by HCLonely** [comment]
麻烦发一下你的站点连接，我试了是没问题的
![example](https://user-images.githubusercontent.com/26346802/147913929-52ae281f-1621-429e-ae43-ae8b930de2a2.gif)

**Comment by WhitePaper233** [comment]
https://whitepaper233.top/bangumis/index.html

**Comment by HCLonely** [comment]
更新一下应该可以了

**Comment by WhitePaper233** [comment]
感谢，问题已解决！
