### ISSUE TITLE
关于插件使用后封面修改问题

### ISSUE THREAD

**Issue by Shenyan-Wu** [HCLonely/hexo-bilibili-bangumi#12]
**错误描述**

插件显示了追剧信息，但是顶部封面无法修改了
**报错信息（建议使用截图，请尽量截取全部把错误信息）**

![P4~L@MWE@L@VXR}~MSEC3(H](https://user-images.githubusercontent.com/66053052/107517182-60781800-6be8-11eb-8f54-2fb8e142001b.png)

**插件版本**

**软件信息（使用`hexo -v`命令查看）**

**Comment by HCLonely** [comment]
这个是你主题中配置的，跟插件无关

**Comment by Shenyan-Wu** [comment]
好吧大佬我找到问题所在了

**Comment by HiderX** [comment]
> 好吧大佬我找到问题所在了

问题怎么解决的？
