### ISSUE TITLE
请问运行报错是怎么回事

### ISSUE THREAD

**Issue by imouup** [HCLonely/hexo-bilibili-bangumi#124]
**报错信息（建议使用截图，请尽量截取全部把错误信息）**
![截图](https://cdn.jsdelivr.net/gh/imouup/pico/pic115230.png)

`INFO  Validating config
INFO  Getting bangumis, please wait...
(node:332) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.88.20:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**插件版本**
 1.7.2 

**软件信息（使用`hexo -v`命令查看）**
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 13.14.0
v8: 7.9.317.25-node.32
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 79
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0

**Comment by HCLonely** [comment]
连接超时

**Comment by imouup** [comment]
谢谢，已经解决了
