### ISSUE TITLE
[BUG] 连接超时

### ISSUE THREAD

**Issue by Niko-Karen** [HCLonely/hexo-bilibili-bangumi#125]
**错误描述**
我已阅读[issus](https://github.com/HCLonely/hexo-bilibili-bangumi/issues/124)。我也是这个错误，但无论我怎么换代理怎么换VPN都没用，不知前面那位是怎么解决的？下面是截图。

**报错信息（建议使用截图，请尽量截取全部把错误信息）**
![屏幕截图 2022-01-30 184759](https://user-images.githubusercontent.com/91728467/151696612-001e9402-5887-48b6-a4b5-ef6afdb3b37a.png)

报错内容有一个json，太长了，截不完.

**插件版本**
Version: `1.7.2`

**软件信息（使用`hexo -v`命令查看）**
hexo: 5.4.1
hexo-cli: 4.3.0
os: win32 10.0.22000
node: 16.13.1
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

**Comment by HCLonely** [comment]
目前不支持代理，下个版本将添加代理功能并修复此问题

**Comment by Niko-Karen** [comment]
> 目前不支持代理，下个版本将添加代理功能并修复此问题

收到！感谢大大！
