### ISSUE TITLE
[BUG] butterfly主题下无法配置页面头图

### ISSUE THREAD

**Issue by HiderX** [HCLonely/hexo-bilibili-bangumi#127]
**错误描述**

butterfly主题下无法配置页面头图
**报错信息（建议使用截图，请尽量截取全部把错误信息）**

![image](https://user-images.githubusercontent.com/60884197/160747501-83ce7316-0534-47a5-a7b6-af6c77c70ce2.png)

**插件版本**

npm 安装版本
**软件信息（使用`hexo -v`命令查看）**

![image](https://user-images.githubusercontent.com/60884197/160747630-bb66d148-6d03-4a50-ae11-c801f819c4ea.png)

**Comment by HCLonely** [comment]
![image](https://user-images.githubusercontent.com/26346802/160810423-d33ed82a-03f9-41db-aa71-4b25f799d7fc.png)

**Comment by HiderX** [comment]
谢谢。问个题外话，请问您知道怎么关闭主页的头像旋转吗？彻底关闭它，仅仅关闭effect 头像还是会在鼠标移动到头像上方时旋转

**Comment by HCLonely** [comment]
> 谢谢。问个题外话，请问您知道怎么关闭主页的头像旋转吗？彻底关闭它，仅仅关闭effect 头像还是会在鼠标移动到头像上方时旋转

不知道，主题文档里应该有吧

**Comment by HiderX** [comment]
> > 谢谢。问个题外话，请问您知道怎么关闭主页的头像旋转吗？彻底关闭它，仅仅关闭effect 头像还是会在鼠标移动到头像上方时旋转
> 
> 不知道，主题文档里应该有吧
主题文档里只介绍了如何关闭effect，并不能彻底关闭旋转，我用的是butterfly主题。感谢您的回复
