### ISSUE TITLE
翻页时可能出现图片无法显示的问题

### ISSUE THREAD

**Issue by EmptyDreams** [HCLonely/hexo-bilibili-bangumi#131]
### 问题描述及如何重现此问题

进入页面后，如果翻页时要显示的那一页之前已经显示过了图片就会无法加载。

比如我先翻到第二页，再翻到第一页，那么第一页的所有图片都变得无法加载。

---

我猜测可能和懒加载有关：

1. 同时关闭主题自带的和bangumi的懒加载时图片第一次也无法显示
2. 只开启主题自带的懒加载时图片第一次可以显示
3. 只开启bangumi的懒加载时问题消失

---

我是用的主题是`butterfly`

![image](https://user-images.githubusercontent.com/44894906/165110423-a7216926-c8e2-4475-8e6a-b1b42e4c674f.png)

具体效果可以在我的博客测试：https://kmar.top/bangumis/

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

后台没有任何报错

### 插件版本

1.7.4

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.1.0
hexo-cli: 4.3.0
os: win32 10.0.19043
node: 16.14.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1m+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by HCLonely** [comment]
lazyload冲突了，你可以在这个页面把主题的lazyload关了，用插件的lazyload
```yaml
bangumi:
  lazyload: true
  extra_options:
    lazyload:
      enable: false
```

**Comment by EmptyDreams** [comment]
> lazyload冲突了，你可以在这个页面把主题的lazyload关了，用插件的lazyload
> 
> ```yaml
> bangumi:
>   lazyload: true
>   extra_options:
>     lazyload:
>       enable: false
> ```

如果是lazyload冲突的话为啥我关了bangumi的还会冲突嘞⊙︿⊙
而且两个lazyload都不开直接显示不出来了

**Comment by HCLonely** [comment]
> > lazyload冲突了，你可以在这个页面把主题的lazyload关了，用插件的lazyload
> > ```yaml
> > bangumi:
> >   lazyload: true
> >   extra_options:
> >     lazyload:
> >       enable: false
> > ```
> 
> 如果是lazyload冲突的话为啥我关了bangumi的还会冲突嘞⊙︿⊙ 而且两个lazyload都不开直接显示不出来了

应该是其他哪个功能也冲突了，直接把图片的链接改为`null`了

**Comment by EmptyDreams** [comment]
> > > lazyload冲突了，你可以在这个页面把主题的lazyload关了，用插件的lazyload
> > > ```yaml
> > > bangumi:
> > >   lazyload: true
> > >   extra_options:
> > >     lazyload:
> > >       enable: false
> > > ```
> > 
> > 
> > 如果是lazyload冲突的话为啥我关了bangumi的还会冲突嘞⊙︿⊙ 而且两个lazyload都不开直接显示不出来了
> 
> 应该是其他哪个功能也冲突了，直接把图片的链接改为`null`了

bangumi的lazyload可以在全站生效吗？

**Comment by HCLonely** [comment]
> > > > lazyload冲突了，你可以在这个页面把主题的lazyload关了，用插件的lazyload
> > > > ```yaml
> > > > bangumi:
> > > >   lazyload: true
> > > >   extra_options:
> > > >     lazyload:
> > > >       enable: false
> > > > ```
> > > 
> > > 
> > > 如果是lazyload冲突的话为啥我关了bangumi的还会冲突嘞⊙︿⊙ 而且两个lazyload都不开直接显示不出来了
> > 
> > 
> > 应该是其他哪个功能也冲突了，直接把图片的链接改为`null`了
> 
> bangumi的lazyload可以在全站生效吗？

只在番剧页生效

**Comment by HCLonely** [comment]
图片加载相关问题(#134)
