### ISSUE TITLE
翻页后无法查看封面大图

### ISSUE THREAD

**Issue by EmptyDreams** [HCLonely/hexo-bilibili-bangumi#133]
### 问题描述及如何重现此问题

每一个分类的第一页都正常，翻到后面的页码内就无法查看大图，效果见下图

我开启了bangumis的懒加载，没有启用主题内置的

![Screenshot_20220505_095125_com huawei browser](https://user-images.githubusercontent.com/44894906/166853353-1f264049-bca8-4772-bd66-95ee76eaa436.jpg)

真实效果见：https://kmar.top/bangumis/

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

手机上看不了后台，应该是没有报错

### 插件版本

1.7.4

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.1.0
hexo-cli: 4.3.0
os: win32 10.0.19043
node: 16.14.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1m+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by HCLonely** [comment]
主题`source/js/utils.js`文件235行改为`const dataSrc = i.dataset.lazySrc || i.getAttribute('data-src') || i.src`
![image](https://user-images.githubusercontent.com/26346802/166860781-05b5ffc5-cee5-4a87-b5a7-b265fc9cb927.png)

**Comment by HCLonely** [comment]
图片加载相关问题(#134)
