### ISSUE TITLE
关于配置完成后番剧界面不显示的问题

### ISSUE THREAD

**Issue by cfx2020** [HCLonely/hexo-bilibili-bangumi#137]
配置完成后番剧界面没有番剧显示，我是fulid主题[https://cfx2020.netlify.app/bangumis/](url)，我通过netlify部署，仓库为[https://github.com/cfx2020/hexo-blog-netlify/](url)，我不知道问题是不是出在这个文件上面[https://github.com/cfx2020/hexo-blog-netlify/blob/main/package.json](url)，也许是那行`"bangumi": "hexo bangumi -u",`没有工作？

**Comment by HCLonely** [comment]
不需要`"bangumi": "hexo bangumi -u"`

**Comment by cfx2020** [comment]
将这行删掉之后也无效，因为仓库不在本地，我也用不了hexo命令。因为是第一次玩博客，还请大佬帮忙看看

**Comment by HCLonely** [comment]
你部署时不是需要`hexo generate`或`hexo deploy`吗，在`hexo generate`或`hexo deploy`之前使用`hexo bangumi -u`命令更新追番数据

**Comment by cfx2020** [comment]
感谢，我明白了，这个问题已经在netfily配置好了。还有一点就是，为什么番剧页有些番剧的简介没有显示，而是只有竖着的简介两个字

**Comment by HCLonely** [comment]
简介问题已修复

**Comment by cfx2020** [comment]
好的，谢谢大佬
