### ISSUE TITLE
[New Feature]: 关闭侧边栏和评论功能

### ISSUE THREAD

**Issue by wang-xiaowu** [HCLonely/hexo-bilibili-bangumi#156]
### 功能描述

作者你好, 请问能否添加个关闭侧边栏和评论的功能,类似douban

**Comment by HCLonely** [comment]
能不能详细描述一下，我不明白你说的什么意思

**Comment by wang-xiaowu** [comment]
> 能不能详细描述一下，我不明白你说的什么意思

douban提供了这两个参数以供评论和侧边栏的关闭与否

![image](https://user-images.githubusercontent.com/44340137/177673528-473bd4d5-f76b-46bb-a0b9-087bfd81e0bb.png)

**Comment by wang-xiaowu** [comment]
> 边栏和评论的功能,类似douban

我的侧边栏插件有点多, 如果我没有追剧或者追番, 它会呈现出很大一片空白的情况

**Comment by HCLonely** [comment]
这两个选项写在`extra_options`里就行
