### ISSUE TITLE
[Bug]: Unhandled rejection TypeError

### ISSUE THREAD

**Issue by Crazyokd** [HCLonely/hexo-bilibili-bangumi#166]
### 问题描述及如何重现此问题

当我填写好配置参数并试图去访问相应链接时（比如//myblog/bili/index.html），就会出现如下错误。

鉴于该项目参考自[hexo-douban]()，我又去配置了相应的豆瓣页，发现触发时机和报错反馈都是相同的。

由于本人并不懂前端知识，暗自猜测错误可能是由于该项目与我所使用的[nexmoe](https://github.com/theme-nexmoe/hexo-theme-nexmoe)主题之间的冲突。但对于解决方案就毫无头绪了。

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

<img width="755" alt="image" src="https://user-images.githubusercontent.com/74645100/179954632-63b5cf69-4c7e-4ade-9201-1a716bf301af.png">

### 插件版本

1.8.0

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.2.0
hexo-cli: 4.3.0
os: linux 5.10.102.1-microsoft-standard-WSL2 Ubuntu 20.04.3 LTS (Focal Fossa)
node: 17.5.0
v8: 9.6.180.15-node.13
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 3.0.1+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
```

**Comment by HCLonely** [comment]
已修复
