### ISSUE TITLE
[New Feature]: 通过API获取bgm的信息

### ISSUE THREAD

**Issue by Trrrrw** [HCLonely/hexo-bilibili-bangumi#182]
### 功能描述

bgm源获取不了详细信息，可以试试这个[https://github.com/bangumi/api/](https://github.com/bangumi/api/)

**Comment by Trrrrw** [comment]
啊，好像不是这样![](https://img4.nga.178.com/ngabbs/post/smile/ac15.png)。但我用bgm源确实只有封面和标题。

**Comment by MareDevi** [comment]
> 啊，好像不是这样![](https://camo.githubusercontent.com/7999000ae4523d9f2227efe706fd9b8799f19d9f525c6b5c3ee79a6f394cc6b9/68747470733a2f2f696d67342e6e67612e3137382e636f6d2f6e67616262732f706f73742f736d696c652f616331352e706e67)。但我用bgm源确实只有封面和标题。

我也是

**Comment by Trrrrw** [comment]
> > 啊，好像不是这样![](https://camo.githubusercontent.com/7999000ae4523d9f2227efe706fd9b8799f19d9f525c6b5c3ee79a6f394cc6b9/68747470733a2f2f696d67342e6e67612e3137382e636f6d2f6e67616262732f706f73742f736d696c652f616331352e706e67)。但我用bgm源确实只有封面和标题。
> 
> 我也是

可以试试这个[https://www.trrw.tech/hexo-bilibili-bangumi-addon/](https://www.trrw.tech/hexo-bilibili-bangumi-addon/)，自己写的，可能不是很好但能用。（只会Python╮⁠(⁠＾⁠▽⁠＾⁠)⁠╭）

**Comment by MareDevi** [comment]
> > > 啊，好像不是这样![](https://camo.githubusercontent.com/7999000ae4523d9f2227efe706fd9b8799f19d9f525c6b5c3ee79a6f394cc6b9/68747470733a2f2f696d67342e6e67612e3137382e636f6d2f6e67616262732f706f73742f736d696c652f616331352e706e67)。但我用bgm源确实只有封面和标题。
> > 
> > 
> > 我也是
> 
> 可以试试这个https://www.trrw.tech/hexo-bilibili-bangumi-addon/，自己写的，可能不是很好但能用。（只会Python╮⁠(⁠＾⁠▽⁠＾⁠)⁠╭）

好的谢谢
