### ISSUE TITLE
大佬，运行报错

### ISSUE THREAD

**Issue by cjyx9** [HCLonely/hexo-bilibili-bangumi#2]
INFO  Getting bilibili bangumis, please wait...
(node:6496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'total' of undefined
    at getBangumiPage (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:44:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async biliBangumi (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:78:14)
    at async saveBangumiData (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:89:19)
(node:6496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HCLonely** [comment]
> INFO Getting bilibili bangumis, please wait...
> (node:6496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'total' of undefined
> at getBangumiPage (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:44:39)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async biliBangumi (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:78:14)
> at async saveBangumiData (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:89:19)
> (node:6496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:6496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

你更新一下，看看还会报什么错

**Comment by cjyx9** [comment]
```
$ hexo bangumi update

INFO  Getting bilibili bangumis, please wait...
(node:10532) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'total' of undefined
    at getBangumiPage (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:44:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async biliBangumi (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:78:14)
    at async saveBangumiData (C:\Users\CT\Desktop\blog\myblog\node_modules\hexo-bilibili-bangumi\index.js:89:19)
(node:10532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cjyx9** [comment]
好了，谢谢大佬
```
$ hexo bangumi update
INFO  Getting bilibili bangumis, please wait...
Get bangumi data error: 0
Get bangumi data error: 0
INFO  4 bangumis have been loaded in 580 ms
INFO  Bilibili bangumis data has been saved
```
