### ISSUE TITLE
出现about:blank#blocked空白页面

### ISSUE THREAD

**Issue by iven13465** [HCLonely/hexo-bilibili-bangumi#212]
### 问题描述及如何重现此问题

点击上一页和下一页这类按钮会在新标签页打开about:blank#blocked空白页面

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

![image](https://user-images.githubusercontent.com/95957360/199251994-e339073f-40dd-43c1-8012-6223e802930b.png)
好像是这个target="_blank"的问题，但文件中的相关代码没有问题啊
![image](https://user-images.githubusercontent.com/95957360/199252778-67eeb612-98d5-41ca-92b0-dabc06577b6a.png)

### 插件版本

1.8.3 主题：matery

### 环境信息（使用`hexo -v`命令查看）

```shell
$ hexo -v
INFO  Validating config
hexo: 6.2.0
hexo-cli: 4.3.0
os: win32 10.0.22000
node: 16.15.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 1.1.1n+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by HCLonely** [comment]
这是主题自动将target改成_blank了

**Comment by bilibiliworld** [comment]
> 这是主题自动将target改成_blank了

应该怎么修改呢？

**Comment by HCLonely** [comment]
> > 这是主题自动将target改成_blank了
> 
> 应该怎么修改呢？

去问主题作者

**Comment by bilibiliworld** [comment]
就matery主题来说，解决办法是删除source/js/matery.js里的$('#articleContent a').attr('target', '_blank');这一行
