### ISSUE TITLE
请问如何修改番剧封面尺寸

### ISSUE THREAD

**Issue by lissettecarlr** [HCLonely/hexo-bilibili-bangumi#266]
发现这封面大了一点点，试了下将图中的width修改为100px正好合适，但是不知道改那里。 请问怎么改样式最方便呢，主题是fluid，这里是图片：https://i.imgtg.com/2023/03/08/YDwZp.png

**Comment by HCLonely** [comment]
直接添加css就行

**Comment by lissettecarlr** [comment]
额，抱歉，不知道在哪儿添加，对前端一穷二白。

**Comment by HCLonely** [comment]
https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html
```yml
custom_head: '<style>.bangumi-picture{width:100px !important}</style>'
```

**Comment by lissettecarlr** [comment]
十分感谢
