### ISSUE TITLE
请问如何修改此处浅蓝色字体

### ISSUE THREAD

**Issue by QiuWeimengChan** [HCLonely/hexo-bilibili-bangumi#271]
![image](https://user-images.githubusercontent.com/68499659/227779024-0e49dfb1-b7be-44bb-a55d-411b2fb97cd4.png)
主题是hexo-theme-fluid 1.9.4
hexo-bilibili-bangumi版本是1.8.5
已经设置
metaColor: #2c3e50
color: #3c4858

hexo -v 提示
hexo: 6.2.0
hexo-cli: 4.3.0
os: win32 10.0.22621
node: 16.14.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1m+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

**Comment by QiuWeimengChan** [comment]
尝试根据浏览器调试定位到的bangumi-picture的信息，重新修改一下index.css，但是发现好像没啥用。尝试根据浏览器调试定位到的浅蓝色#2fd8d8，也没有发现在Fluid相关配置里，头晕了😵

**Comment by HCLonely** [comment]
十六进制颜色代码需要加引号`metaColor: '#2c3e50'`

**Comment by QiuWeimengChan** [comment]
> 十六进制颜色代码需要加引号`metaColor: '#2c3e50'`

好的，谢谢。请问排版问题如何修复？图片和栏明显不对，打开评论功能直接错乱了…

**Comment by HCLonely** [comment]
主题兼容性问题，可以自己添加css调整，插件无法对所有主题进行适配

**Comment by QiuWeimengChan** [comment]
> 主题兼容性问题，可以自己添加css调整，插件无法对所有主题进行适配

好的，谢谢。咱研究一下，如果可以的话，可以提交PR给吗

**Comment by HCLonely** [comment]
可以，我之后会更新支持多主题的版本，你只需要添加相应的css文件即可

**Comment by HCLonely** [comment]
参考https://github.com/HCLonely/hexo-bilibili-bangumi#%E5%A4%9A%E4%B8%BB%E9%A2%98%E5%85%BC%E5%AE%B9 提交PR

**Comment by QiuWeimengChan** [comment]
> 可以，我之后会更新支持多主题的版本，你只需要添加相应的css文件即可

不行，咱太菜了啥也写不出来，一行居中都搞不定。咱学习一下css再说😥

**Comment by QiuWeimengChan** [comment]
![image](https://user-images.githubusercontent.com/68499659/227975512-cfc141a7-1c8a-477c-99ee-2d2fbf14ee28.png)
![image](https://user-images.githubusercontent.com/68499659/227976394-aa62065f-715e-4d90-aefe-1de517cd4ce2.png)
![image](https://user-images.githubusercontent.com/68499659/227975356-70b80eee-7826-4f08-90db-ef4267e6a17d.png)
大致适配了一下，但是目前存在一些问题，这个星星如何变得正常。

**Comment by QiuWeimengChan** [comment]
> 可以，我之后会更新支持多主题的版本，你只需要添加相应的css文件即可

大致修好了，排版。请大佬检阅，以及发现一处bug
`.bangumi-starlight.stars8 {
 width:405px
}`
应该修改为
`.bangumi-starlight.stars8 {
 width:405px
}`

![image](https://user-images.githubusercontent.com/68499659/227986866-f1b1976d-ad94-43ab-a383-c7ce5e8c10d1.png)

**Comment by HCLonely** [comment]
改的很好:+1:
