### ISSUE TITLE
[Bug]: 使用bangumi源時報錯

### ISSUE THREAD

**Issue by nagongze** [HCLonely/hexo-bilibili-bangumi#284]
### 问题描述及如何重现此问题

<img width="248" alt="CleanShot 2023-04-19 at 11 22 47" src="https://user-images.githubusercontent.com/68653451/232958883-3ed73947-872d-4bfa-9ba8-d08be4aae309.png">
<img width="348" alt="CleanShot 2023-04-19 at 11 23 12" src="https://user-images.githubusercontent.com/68653451/232958951-82e8ad2e-e017-4536-9a3e-24dcd528dd5c.png">

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

Get bangumi data error: 用户隐私设置未公开

### 插件版本

1.8.2

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.3.0
hexo-cli: 4.3.0
os: darwin 22.1.0 13.0

node: 19.9.0
acorn: 8.8.2
ada: 1.0.4
ares: 1.19.0
brotli: 1.0.9
cldr: 42.0
icu: 72.1
llhttp: 8.1.0
modules: 111
napi: 8
nghttp2: 1.52.0
openssl: 1.1.1t
simdutf: 3.2.3
tz: 2022e
undici: 5.21.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.16
v8: 10.8.168.25-node.16
zlib: 1.2.11
```

**Comment by HCLonely** [comment]
请更新插件至最新版
