### ISSUE TITLE
关于图片加载不出来的问题

### ISSUE THREAD

**Issue by BlueHeart0621** [HCLonely/hexo-bilibili-bangumi#33]
**错误描述**
直接访问页面或刷新页面，其他数据都能加载出来，但番剧的图像加载不出来，一直显示在 Loading 状态（这里我是设置了 loading 值，所以 loading 的图片和默认的不一样）
![image](https://user-images.githubusercontent.com/42397957/114312866-c7517900-9b26-11eb-8e50-37f9e33f5ad3.png)

但点击一下「下一页」，又能加载出图像：
![image](https://user-images.githubusercontent.com/42397957/114312997-4e9eec80-9b27-11eb-9897-0c90d8137d67.png)

**插件版本**
hexo-bilibili-bangumi@1.5.4

**软件信息（使用`hexo -v`命令查看）**
hexo-cli: 4.2.0
os: Linux 5.12.0-1-MANJARO linux x64
node: 15.12.0
v8: 8.6.395.17-node.27
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 88
nghttp2: 1.43.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1j
cldr: 38.1
icu: 68.2
tz: 2020d
unicode: 13.0

**Comment by HCLonely** [comment]
连接发一下

**Comment by BlueHeart0621** [comment]
https://blueheart0621.gitee.io/

**Comment by HCLonely** [comment]
这应该是你装的某个插件把图片的链接改了，你把图片有关的插件关了试试

**Comment by BlueHeart0621** [comment]
ok，我试试，谢谢了
