### ISSUE TITLE
能否添加一个排序的功能，就像 bgm自带的那种

### ISSUE THREAD

**Issue by bilibiliworld** [HCLonely/hexo-bilibili-bangumi#350]
### 功能描述

主要是希望能够按评分排序，不然总是最近添加的在上面~

p.s. 使用bgm源并配置代理，showMyComment设置为true后，仍不能显示自己的评分和评价

**Comment by HCLonely** [comment]
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/26346802/5b97d06b-18ff-4972-891e-4ef0c66435ea)
自己的评分和评价可以正常显示
