### ISSUE TITLE
[New Feature]: 支持调用bangumi用户中的游戏列表

### ISSUE THREAD

**Issue by AkiCCLing** [HCLonely/hexo-bilibili-bangumi#391]
### 功能描述

大体界面如同追番列表一样，分为想玩 在玩

**Comment by HCLonely** [comment]
目前官方和第三方都没有提供获取游戏数据的api, 暂无支持计划

**Comment by bilibiliworld** [comment]
使用hexo game -u可以更新游戏数据，但没有创建对应文件夹和index文件

**Comment by HCLonely** [comment]
`hexo generate`后会生成对应页面

**Comment by HCLonely** [comment]
> 使用hexo game -u可以更新游戏数据，但没有创建对应文件夹和index文件

`hexo generate`后会生成对应页面

**Comment by bilibiliworld** [comment]
> > 使用hexo game -u可以更新游戏数据，但没有创建对应文件夹和index文件
> 
> `hexo generate`后会生成对应页面

然而并不会，并没有生成对应文件夹和页面，hexo核心版本是6.3
![PixPin_2024-09-22_23-08-44](https://github.com/user-attachments/assets/c04523b8-4c00-462a-a631-eb60e5fd8042)

**Comment by bilibiliworld** [comment]
![image](https://github.com/user-attachments/assets/5f9f9b84-8cb1-435b-aeb8-093bc07aafdf)
/source/_data里有抓取到的json数据

**Comment by HCLonely** [comment]
> > > 使用hexo game -u可以更新游戏数据，但没有创建对应文件夹和index文件
> > 
> > 
> > `hexo generate`后会生成对应页面
> 
> 然而并不会，并没有生成对应文件夹和页面，hexo核心版本是6.3 ![PixPin_2024-09-22_23-08-44](https://private-user-images.githubusercontent.com/70128832/369697395-c04523b8-4c00-462a-a631-eb60e5fd8042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg0OTIsIm5iZiI6MTcyNzMzODE5MiwicGF0aCI6Ii83MDEyODgzMi8zNjk2OTczOTUtYzA0NTIzYjgtNGMwMC00NjJhLWE2MzEtZWI2MGU1ZmQ4MDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4MDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDcyZGU2NjFlMzU5NzAzNTIwN2UyODIwMDU0MGZjNGM2MjFlZGM1MzMyMWE0MDc4YzdmMjZjZDhjNTkxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7c8Woq38L1ANjkhnqdwo0FU6fV7pimVDaCzoV-cnGV0)

插件配置和generate后的完整日志发一下

**Comment by bilibiliworld** [comment]
> > > > 使用hexo game -u可以更新游戏数据，但没有创建对应文件夹和index文件
> > > 
> > > 
> > > `hexo generate`后会生成对应页面
> > 
> > 
> > 然而并不会，并没有生成对应文件夹和页面，hexo核心版本是6.3 ![PixPin_2024-09-22_23-08-44](https://private-user-images.githubusercontent.com/70128832/369697395-c04523b8-4c00-462a-a631-eb60e5fd8042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg0OTIsIm5iZiI6MTcyNzMzODE5MiwicGF0aCI6Ii83MDEyODgzMi8zNjk2OTczOTUtYzA0NTIzYjgtNGMwMC00NjJhLWE2MzEtZWI2MGU1ZmQ4MDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4MDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDcyZGU2NjFlMzU5NzAzNTIwN2UyODIwMDU0MGZjNGM2MjFlZGM1MzMyMWE0MDc4YzdmMjZjZDhjNTkxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7c8Woq38L1ANjkhnqdwo0FU6fV7pimVDaCzoV-cnGV0)
> 
> 插件配置和generate后的完整日志发一下

![Clip_2024-10-01_23-42-33](https://github.com/user-attachments/assets/2063c38d-ebb6-4c59-86b7-17e8c51e4420)

**Comment by bilibiliworld** [comment]
完整日志是要包含其他的吗，那有点太长了，我这边只发了games相关的，如果需要我再补上

**Comment by HCLonely** [comment]
> 完整日志是要包含其他的吗，那有点太长了，我这边只发了games相关的，如果需要我再补上

应该是和hexo-douban插件冲突了，更新到最新版试试

**Comment by bilibiliworld** [comment]
> > 完整日志是要包含其他的吗，那有点太长了，我这边只发了games相关的，如果需要我再补上
> 
> 应该是和hexo-douban插件冲突了，更新到最新版试试

可以了，感谢
