### ISSUE TITLE
增加番剧简介的截取长度

### ISSUE THREAD

**Issue by HaoTian22** [HCLonely/hexo-bilibili-bangumi#4]
希望可以增加番剧简介的截取长度
不然后面虽然有大量的空间，但是信息依然显示不全，感觉有点奇怪
(如图希望可以添加简介截取长度的选项来利用好后面的空间)
![image](https://user-images.githubusercontent.com/48882584/81397530-1d20e280-915a-11ea-9b0f-d1355cb07739.png)

**Comment by HCLonely** [comment]
这个不是自动截的，获取到的数据只有这么多
