### ISSUE TITLE
[New Feature]: 调用B站Cover封面增加图片镜像缓存服务

### ISSUE THREAD

**Issue by SaboZhang** [HCLonely/hexo-bilibili-bangumi#452]
### 功能描述

使用过程中发现调用B站图片403了，自己试了一下增加 `<meta name="referrer" content="no-referrer" />`标签不好使，然后尝试使用镜像服务封面图片可以正常显示，我也在自己本地尝试修改之后，可以正常使用，大佬是否接受pr 或者是可以实现这个功能吗？我是尝试增加了一个配置字段来实现的
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/34998007/ff9ef511-a806-4251-9006-9d700313c681)
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/34998007/2417274f-0788-4e85-9e75-51e22550d35a)
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/34998007/31810fa2-44b6-4ab6-accc-760426cf8590)

**Comment by HCLonely** [comment]
欢迎pr
