### ISSUE TITLE
[Bug]: 有关第一次进入界面，出现三个翻页条，刷新后恢复的问题

### ISSUE THREAD

**Issue by sunyrain** [HCLonely/hexo-bilibili-bangumi#465]
### 问题描述及如何重现此问题

![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/89635780/40aa3cb4-287c-4a06-bf0c-90eabebfe7d9)
以上是刷新以后的结果，有两个是hide，一个是show显示正常，但是直接进入的话，就是下面这种情况，三个界面似乎同时显示了。
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/89635780/26ae7662-9358-4bdf-8d87-dd3337c8f23b)
以下是参考图
正常情况下：
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/89635780/fa731c1f-d2ae-4feb-a5da-c8c63f382c21)
异常情况：
![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/89635780/7520dd87-7dd8-4685-8702-6378ea6cb9e7)

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

没有报错

### 插件版本

1.9.0

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.2.0
hexo-cli: 4.3.1
os: win32 10.0.19045
node: 21.7.1
acorn: 8.11.3
ada: 2.7.6
ares: 1.27.0
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 44.1
icu: 74.2
llhttp: 9.1.3
modules: 120
napi: 9
nghttp2: 1.60.0
nghttp3: 0.7.0
ngtcp2: 1.3.0
openssl: 3.0.13+quic
simdjson: 3.7.0
simdutf: 4.0.8
tz: 2024a
undici: 6.6.2
unicode: 15.1
uv: 1.48.0
uvwasi: 0.0.20
v8: 11.8.172.17-node.20
zlib: 1.3.0.1-motley-40e35a7
```

**Comment by sunyrain** [comment]
进入页面后点击右上角，bangumi

**Comment by HCLonely** [comment]
pjax问题，解决办法（2选1）：
1. 关闭pjax
2. 修改pjax相关代码，让页面加载完成后重新运行本插件的script

**Comment by sunyrain** [comment]
OK，解决了，谢谢！
