### ISSUE TITLE
[Bug]:‘看过’的番剧并不能全部显示出来 

### ISSUE THREAD

**Issue by Physics-nya** [HCLonely/hexo-bilibili-bangumi#486]
### 问题描述及如何重现此问题

配置主题为Hexo-Fluid，发现‘看过’番剧仅有一部分，有一部分显示不出来。

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

<img width="283" alt="image" src="https://github.com/user-attachments/assets/438447ca-dea3-4b62-97c3-28b2921f4079">

<img width="404" alt="image" src="https://github.com/user-attachments/assets/8761dc0e-0733-4d25-98a9-eb6649d7ddb1">

具体可以至此查看：https://physics-nya.github.io/bangumi/

### 插件版本

10.8.2

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 7.3.0
hexo-cli: 4.3.1
os: win32 10.0.22631
node: 20.11.1
acorn: 8.11.2
ada: 2.7.4
ares: 1.20.1
base64: 0.5.1
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.58.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.13+quic
simdutf: 4.0.4
tz: 2023c
undici: 5.28.3
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.19
v8: 11.3.244.8-node.17
zlib: 1.2.13.1-motley-5daffc7
```

**Comment by Physics-nya** [comment]
顺便问一下，dalao有没有意向把书籍、游戏之类的也放进插件里面来？

**Comment by HCLonely** [comment]
发一下配置

**Comment by Physics-nya** [comment]
_config.yml文件：
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 菲兹克斯喵的blog
subtitle: 'Nyaa~'
description: ''
keywords:
author: 菲兹克斯喵
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://Physics-nya.github.io
root: //
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [myjs/**]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked: 
  prependRoot: true
  postAsset: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: 
    github: 'git@github.com:Physics-nya/Physics-nya.github.io.git'
    gitee: 'https://gitee.com/physics-nya/physics-nya.gitee.io.git'
  branch: 'master' 

math:
  engine: katex
  katex:
    css: https://fastly.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css
    js: https://fastly.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js
    config:
      # KaTeX config
      throwOnError: false
      errorColor: "#cc0000"

# Security
encrypt:
  enable: true

bangumi: 

  enable: true
# 数据源
  source: bgm
# 获取Bangumi番剧信息时使用的Api，仅使用Bangumi源时此选项生效，`bgmApi`: Bangumi Api, `bgmSub`: Bangumi-Subject
  bgmInfoSource: 'bgmv0'
# 就是上面生成页面的地址
  path: bangumi/index.html
# Bangumi的用户id，直接点到个人主页看头像那里就有
  vmid: llr
# 页面的标题
  title: '追番列表'
# 页头的话
  quote: 'Eclipse first, the rest nowhere.'
# 初始显示页面：`0: 想看`, `1: 在看`, `2: 看过`，默认为`1`
  show: 1
# 是否启用图片懒加载，如果与主题的懒加载冲突请关闭
  lazyload: true
# 设置封面图的默认`src`值, `__image__`为封面链接, `__loading__`为loading图片链接, `lazyload`选项为`false`时此选项生效
  srcValue: '__image__'
# 设置封面图的属性与属性值, 例`lazyloadAttrName: 'data-src=__image__'`代表为`img`元素添加`data-src`属性, 其值为图片链接, `lazyload`选项为`false`时此选项生效
  lazyloadAttrName: 'data-src=__image__'
# 图片加载完成前的 loading 图片，需启用图片懒加载
  loading:
# 使用`bgm`源时显示自己的评价及评论，默认`false`
  showMyComment: true
# 分页优化，只将第一页的数据渲染到`html`文件中，其余数据将通过异步请求加载，避免番剧过多时html文件过大导致页面加载缓慢，建议番剧较多时使用，默认`false`
  pagination: false
# meta 部分(简介上方)字体颜色
  metaColor:
# 简介字体颜色
  color:
# 番剧封面使用`webp`格式(此格式在`safari`浏览器下不显示，但是图片大小可以缩小 100 倍左右，仅支持哔哩哔哩源), 默认`true`
  webp: false
# 获取番剧数据时是否显示进度条，默认`true`
  progress: true
# 手动添加的番剧/追剧数据是否优先显示，`1`为优先，其它为不优先
  extraOrder:
# 此配置会扩展到Hexo`page`变量中
  extra_options:
    key: value
    lazyload:
      enable: false # 关闭主题自带的懒加载(只关闭番剧页，不影响其他页面)

all_minifier: true

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false`

**Comment by HCLonely** [comment]
我测试的没问题
![image](https://github.com/user-attachments/assets/35d63a9c-52ed-4cb7-a125-cf74026f92c9)

看一下`hexo bangumi -u`命令的输出日志

**Comment by Physics-nya** [comment]
```
$ hexo bangumi -u
INFO  Validating config
INFO  Getting bangumis, please wait...



INFO  37 bangumis have been loaded in 5777 ms
```

**Comment by HCLonely** [comment]
是最新版吗，最新版改为`source: bgmv0`

**Comment by Physics-nya** [comment]
```
$ hexo bangumi -u
INFO  Validating config
INFO  Getting bgm bangumi data, please wait...



INFO  96 2s have been loaded in 8016 ms
```
应该是好了，非常感谢！
