### ISSUE TITLE
[Bug]: source 中填写 bangumi 或 bgm 都会出现只能获取第一页的数据，bgmv0 则出现排版错误

### ISSUE THREAD

**Issue by windowBR** [HCLonely/hexo-bilibili-bangumi#499]
### 问题描述及如何重现此问题

当我使用 bgm 或者 bangumi 时仅获取到了 Bangumi 的第一页数据：
![image](https://github.com/user-attachments/assets/faf029b1-6429-4236-8f2d-508345381d21)
![image](https://github.com/user-attachments/assets/27a64778-f62f-41c0-9b05-b899cec77efb)

当我使用 bgmv0 时能获取正常，但出现了排版问题，疑似是我主题没法用进度条：
![image](https://github.com/user-attachments/assets/7c887816-4b34-4e71-9653-b4a1fd4acacd)
![image](https://github.com/user-attachments/assets/5d6b5c45-873f-4326-8435-3d51dbe3a1c6)

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

无

### 插件版本

1.10.1

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.22631
node: 18.20.4
acorn: 8.11.3
ada: 2.7.8
ares: 1.28.1
base64: 0.5.2
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 44.1
icu: 74.2
llhttp: 6.1.1
modules: 108
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.3.0
openssl: 3.0.13+quic
simdutf: 5.2.4
tz: 2024a
undici: 5.28.4
unicode: 15.1
uv: 1.44.2
uvwasi: 0.0.19
v8: 10.2.154.26-node.37
zlib: 1.3.0.1-motley
```

**Comment by windowBR** [comment]
目前我希望的是想试试在使用 bgmv0 的同时不使用追番进度条，但我在 readme 里似乎没找到这个功能的开关？

**Comment by HCLonely** [comment]
`progress: false`关闭进度条

**Comment by windowBR** [comment]
> `progress: false`关闭进度条

这我当然试过，但我希望关掉的是上图这个进度条，这个选项关掉的是下图的进度条，压根不是一个东西啊。。。
![image](https://github.com/user-attachments/assets/8ca1a6ac-3e51-4b2f-bf35-ee6f3872f4b2)
![image](https://github.com/user-attachments/assets/0814212d-dee7-4115-a6f8-9307a8df21d8)

**Comment by HCLonely** [comment]
v1.10.2版本已修复

**Comment by windowBR** [comment]
> v1.10.2版本已修复

感谢修复，另外我刚刚更新到了最新 1.10.2 版本，再次进行了相关选项调整后发现了排版错误并非进度条引起。
经测试发现原因为在 **同时使用 bgmv0 且开启我的评论（showMyComment: true）** 的情况下才会出现错误，错误状态如该 issue 最开始的截图所示。

**Comment by HCLonely** [comment]
已修复

**Comment by windowBR** [comment]
> 已修复

再次感谢修复，但仍然发现了新的问题，我直接上图吧
首先是 **bgmv0源** 打开评论栏的有评论和无评论的截图：
![image](https://github.com/user-attachments/assets/bcc853a8-6610-4c9b-b176-5a02c7d96e4f)
然后是使用 **bgm源** 其余设置不变：
![image](https://github.com/user-attachments/assets/47879fc2-c9d3-4769-8392-3ff3e174dcc7)
 
问题描述：使用 bgmv0源 并开启评论栏时，首先是无论是否撰写了评论，都会显示一个框；然后有评论的条目也存在一些问题，首先是评论栏的框与封面重合，其次是没有显示个人打分。而 bgm源 的评论框行为则非常符合直觉，有评论的才显示框，并且条目高度增高以正常放置评论栏并显示评分。

**Comment by windowBR** [comment]
补充：对比了各个番剧条目后似乎找到了封面与评论框重合的原因，原因出在 bgmv0源 显示的简介与 bgm源 截断位置不同。bgmv0源 在许多条目的番剧简介截断的位置在我的主题下显示为两行，造成了评论栏位置上移了一行。将浏览器窗口大小缩窄使简介变为三行字后排版恢复正常也验证了这个想法。而 bgm源 则基本不会出现这个问题，截断位置基本都是显示为三行简介。

附图为 bgmv0源 将浏览器窗口缩窄后的表现
![image](https://github.com/user-attachments/assets/babb9d4e-0465-41ca-9f8e-1e3cd1e17175)

**Comment by HCLonely** [comment]
已修复，再试试

**Comment by windowBR** [comment]
再次感谢修复

排版问题相比上一版有缓解，但仍未完全解决
对于无评论、无评分的作品仍然未去除评论栏的显示

下图为浏览器默认最大化窗口大小下，简介分别显示出两行及三行、有评论和评分/有评分无评论/无评分和评论的情况
![image](https://github.com/user-attachments/assets/b1a55664-f0c2-4ddd-a1fb-ce2c1b78c9c2)
下图为同样窗口下简介仅显示一行的情况（简介全长仅能占一行）
![image](https://github.com/user-attachments/assets/2c0859f5-9636-4acb-8db2-3893cdd2f119)

**Comment by HCLonely** [comment]
1. 排版样式已修复；
2. 无评论、无评分的作品去除评论栏的显示需要重新更新数据`hexo bangumi -u`

**Comment by windowBR** [comment]
目前发现的其余问题均已解决
简介不足三行的排版问题仍然存在
![image](https://github.com/user-attachments/assets/8b4b453b-33f8-4a85-ab1b-7d6031aaea22)

已使用当前版本部署到博客上，如果能帮助到 debug 的话可以来看看
[页面链接](https://windowbr.top/bangumis/)

**Comment by HCLonely** [comment]
主题兼容性问题，可以添加自定义样式解决
```css
.bangumi-info {
    min-height: 180px;
}
```

**Comment by windowBR** [comment]
有点不好意思但我其实不太懂这个该怎么改。

姑且说一下我找过的地方吧
我先是按照 README 最后的路径去 hexo 里面的 `/node_modules/hexo-bilibili-bangumi/src/lib/templates/theme/` 添加了个`nexmoe.css` 并填入你提供的代码后，分别 `hexo clean`、`hexo generate`、`hexo s` 进行测试但发现 bangumi-info 仍然是 160px
![image](https://github.com/user-attachments/assets/f852d785-629a-47dd-904d-4af5d9913b75)

然后发现你之前的修复提交多次更改了 `/src/lib/templates/theme/fluid.css` 就尝试去这文件最后加上你提供的代码并测试，情况仍未改变
最后还尝试了将 `/src/lib/templates/index.css` 第 48 行 .bangumi-info 中的 min-height 修改为 180px 似乎也没见生效

知识不到位尝试摸索但没能成功摸索出来，看来还是需要来求助一下😢，实在麻烦您了

**Comment by HCLonely** [comment]
参考你主题的配置说明https://docs.nexmoe.com/v4.2/config/style.html

**Comment by windowBR** [comment]
感谢协助，虽然用的不是这个方法但我最终解决了

因为经测试这个方案并没有作用，会被插件的设置覆盖掉（如下图），但最终我还是成功找到了解决方案
![image](https://github.com/user-attachments/assets/585fbb1b-cdbe-4c31-8abe-5fe57f4e7aed)

其实还是我知识不足的问题，就像我上面说的
> 我先是按照 README 最后的路径去 hexo 里面的 /node_modules/hexo-bilibili-bangumi/src/lib/templates/theme/ 添加了个nexmoe.css 并填入你提供的代码后，分别 hexo clean、hexo generate、hexo s 进行测试但发现 bangumi-info 仍然是 160px

我修改后压根没重新 build，而且直接再 hexo 下这个环境下也没法运行 build（虽然我也不知道原因但总之就是报错），因此其实改了个寂寞。

于是我还是完整的走了遍流程：
1. 将项目 fork 并进行了修改然后 build。
2. 我直接将 build 后的整个项目文件夹复制并覆盖了 hexo 的 node_modules 里面的原文件夹然后进行测试，结果是一切完美
 **我感觉这么直接整个文件夹覆盖是不是会留下什么隐患，但这里我是真不太清楚应该如何操作，希望能得到些指导**
明天我再研究下 pr 相关吧，到时候再交一个 pr 来适配一下这个主题 bug
