### ISSUE TITLE
手机版感觉没适配，基本上都是错位的，能解决吗

### ISSUE THREAD

**Issue by gongdananyou** [HCLonely/hexo-bilibili-bangumi#5]
![dbe7c03dfe732a3de5afb0c9ef6ec40](https://user-images.githubusercontent.com/60178803/85541684-d116f800-b64a-11ea-969d-1e54472a8b25.jpg)

**Comment by HCLonely** [comment]
什么浏览器

**Comment by gongdananyou** [comment]
小米自带的会错位，kiwi只显示前两个，简介后面的都没了

**Comment by HCLonely** [comment]
错位的问题我会修复一下，只显示前两个是正常的，显示多少是根据屏幕宽度来的

**Comment by gongdananyou** [comment]
好的 还有请问下修改字体颜色的位置在哪 就是全多少话这种 这个青色有点太亮了

**Comment by HCLonely** [comment]
下次更新加上

**Comment by gongdananyou** [comment]
好的谢谢

**Comment by HCLonely** [comment]
链接能发一下吗，我这边是没问题的

**Comment by gongdananyou** [comment]
已经解决了 是插件冲突了 还有问下颜色配置是16进制还是英文名称

**Comment by HCLonely** [comment]
都可以，只要浏览器能识别就可以
