### ISSUE TITLE
有无可能直接从bangumi个人主页获取番剧信息？

### ISSUE THREAD

**Issue by Freddd13** [HCLonely/hexo-bilibili-bangumi#54]
现在主要用bangumi的三方App管理追番，而手动添加B站没有的番又不太方便
开成Bug标签了 不好意思

**Comment by Freddd13** [comment]
@HCLonely  推荐项目https://github.com/czy0729/Bangumi  ，您可以看看有没有帮助

**Comment by Freddd13** [comment]
@HCLonely 我试着写了下，已交PR

**Comment by lilyblessing** [comment]
确实，支持bgm了就没可能需要手动添加番剧信息了。bgm的番剧库比bili的全太多了
