### ISSUE TITLE
希望可以自定义番剧页的front_matter参数

### ISSUE THREAD

**Issue by icedtangerine7** [HCLonely/hexo-bilibili-bangumi#87]
很棒的一个插件！
一些主题通过页面的front matter参数来决定是否显示侧边栏和评论等页面元素，如果能支持自定义front matter参数就能在这些主题上控制番剧页面的显示元素了

**Comment by HCLonely** [comment]
在配置中的`extra_options`中添加参数应该就行

**Comment by icedtangerine7** [comment]
> 
> 
> 在配置中的`extra_options`中添加参数应该就行

是这样写吗，添加了之后没有变化（已清理缓存，更新数据库）
![image](https://user-images.githubusercontent.com/25699126/134756143-86105d13-d70e-45c1-8dbf-ebe774a31f5e.png)

**Comment by HCLonely** [comment]
什么主题？

**Comment by icedtangerine7** [comment]
> 什么主题？

Butterfly 
相关信息：https://butterfly.js.org/posts/dc584b87/

**Comment by HCLonely** [comment]
你插件什么版本？

**Comment by icedtangerine7** [comment]
> 
> 
> 你插件什么版本？1.6.1+才可以

是1.6.1

**Comment by icedtangerine7** [comment]
刚才试了一下，居然能用了
